-- 0006_seed_tickers.sql
-- Seed common tickers so the Investments allocation donut + Concentration math
-- have asset_class and leverage_factor for the most popular symbols out of the box.

INSERT OR REPLACE INTO tickers (ticker, name, asset_class, leverage_factor, direction, user_added) VALUES
('VTI', 'Vanguard Total Stock Market ETF', 'US_TOTAL_MARKET', 1.0, 'LONG', 0),
('ITOT', 'iShares Core S&P Total US Stock Market ETF', 'US_TOTAL_MARKET', 1.0, 'LONG', 0),
('SCHB', 'Schwab US Broad Market ETF', 'US_TOTAL_MARKET', 1.0, 'LONG', 0),
('SPTM', 'SPDR Portfolio S&P 1500 Composite Stock Market ETF', 'US_TOTAL_MARKET', 1.0, 'LONG', 0),
('FSKAX', 'Fidelity Total Market Index Fund', 'US_TOTAL_MARKET', 1.0, 'LONG', 0),
('VOO', 'Vanguard S&P 500 ETF', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('SPY', 'SPDR S&P 500 ETF Trust', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('IVV', 'iShares Core S&P 500 ETF', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('QQQ', 'Invesco QQQ Trust', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('VV', 'Vanguard Large-Cap ETF', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('SCHX', 'Schwab US Large-Cap ETF', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('SPLG', 'SPDR Portfolio S&P 500 ETF', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('RSP', 'Invesco S&P 500 Equal Weight ETF', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('FXAIX', 'Fidelity 500 Index Fund', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('VFIAX', 'Vanguard 500 Index Fund Admiral Shares', 'US_LARGE_CAP', 1.0, 'LONG', 0),
('TQQQ', 'ProShares UltraPro QQQ 3x', 'US_LARGE_CAP', 3.0, 'LONG', 0),
('UPRO', 'ProShares UltraPro S&P500 3x', 'US_LARGE_CAP', 3.0, 'LONG', 0),
('SPXL', 'Direxion Daily S&P 500 Bull 3x Shares', 'US_LARGE_CAP', 3.0, 'LONG', 0),
('TMF', 'Direxion Daily 20+ Year Treasury Bull 3x Shares', 'US_BONDS', 3.0, 'LONG', 0),
('TNA', 'Direxion Daily Small Cap Bull 3x Shares', 'US_SMALL_CAP', 3.0, 'LONG', 0),
('UDOW', 'ProShares UltraPro Dow30 3x', 'US_LARGE_CAP', 3.0, 'LONG', 0),
('QLD', 'ProShares Ultra QQQ 2x', 'US_LARGE_CAP', 2.0, 'LONG', 0),
('SSO', 'ProShares Ultra S&P500 2x', 'US_LARGE_CAP', 2.0, 'LONG', 0),
('DDM', 'ProShares Ultra Dow30 2x', 'US_LARGE_CAP', 2.0, 'LONG', 0),
('MVV', 'ProShares Ultra MidCap400 2x', 'US_MID_CAP', 2.0, 'LONG', 0),
('UWM', 'ProShares Ultra Russell2000 2x', 'US_SMALL_CAP', 2.0, 'LONG', 0),
('SQQQ', 'ProShares UltraPro Short QQQ 3x', 'US_LARGE_CAP', 3.0, 'SHORT', 0),
('SPXU', 'ProShares UltraPro Short S&P500 3x', 'US_LARGE_CAP', 3.0, 'SHORT', 0),
('SDOW', 'ProShares UltraPro Short Dow30 3x', 'US_LARGE_CAP', 3.0, 'SHORT', 0),
('SDS', 'ProShares UltraShort S&P500 2x', 'US_LARGE_CAP', 2.0, 'SHORT', 0),
('QID', 'ProShares UltraShort QQQ 2x', 'US_LARGE_CAP', 2.0, 'SHORT', 0),
('TZA', 'Direxion Daily Small Cap Bear 3x Shares', 'US_SMALL_CAP', 3.0, 'SHORT', 0),
('VO', 'Vanguard Mid-Cap ETF', 'US_MID_CAP', 1.0, 'LONG', 0),
('IJH', 'iShares Core S&P Mid-Cap ETF', 'US_MID_CAP', 1.0, 'LONG', 0),
('MDY', 'SPDR S&P MidCap 400 ETF Trust', 'US_MID_CAP', 1.0, 'LONG', 0),
('SCHM', 'Schwab US Mid-Cap ETF', 'US_MID_CAP', 1.0, 'LONG', 0),
('IVOO', 'Vanguard S&P Mid-Cap 400 ETF', 'US_MID_CAP', 1.0, 'LONG', 0),
('VB', 'Vanguard Small-Cap ETF', 'US_SMALL_CAP', 1.0, 'LONG', 0),
('IWM', 'iShares Russell 2000 ETF', 'US_SMALL_CAP', 1.0, 'LONG', 0),
('IJR', 'iShares Core S&P Small-Cap ETF', 'US_SMALL_CAP', 1.0, 'LONG', 0),
('SCHA', 'Schwab US Small-Cap ETF', 'US_SMALL_CAP', 1.0, 'LONG', 0),
('VIOO', 'Vanguard S&P Small-Cap 600 ETF', 'US_SMALL_CAP', 1.0, 'LONG', 0),
('VXUS', 'Vanguard Total International Stock ETF', 'INTL_DEVELOPED', 1.0, 'LONG', 0),
('VEA', 'Vanguard FTSE Developed Markets ETF', 'INTL_DEVELOPED', 1.0, 'LONG', 0),
('IEFA', 'iShares Core MSCI EAFE ETF', 'INTL_DEVELOPED', 1.0, 'LONG', 0),
('SCHF', 'Schwab International Equity ETF', 'INTL_DEVELOPED', 1.0, 'LONG', 0),
('EFA', 'iShares MSCI EAFE ETF', 'INTL_DEVELOPED', 1.0, 'LONG', 0),
('VWO', 'Vanguard FTSE Emerging Markets ETF', 'EMERGING_MARKETS', 1.0, 'LONG', 0),
('IEMG', 'iShares Core MSCI Emerging Markets ETF', 'EMERGING_MARKETS', 1.0, 'LONG', 0),
('EEM', 'iShares MSCI Emerging Markets ETF', 'EMERGING_MARKETS', 1.0, 'LONG', 0),
('SCHE', 'Schwab Emerging Markets Equity ETF', 'EMERGING_MARKETS', 1.0, 'LONG', 0),
('SPEM', 'SPDR Portfolio Emerging Markets ETF', 'EMERGING_MARKETS', 1.0, 'LONG', 0),
('BND', 'Vanguard Total Bond Market ETF', 'US_BONDS', 1.0, 'LONG', 0),
('AGG', 'iShares Core US Aggregate Bond ETF', 'US_BONDS', 1.0, 'LONG', 0),
('TLT', 'iShares 20+ Year Treasury Bond ETF', 'US_BONDS', 1.0, 'LONG', 0),
('IEF', 'iShares 7-10 Year Treasury Bond ETF', 'US_BONDS', 1.0, 'LONG', 0),
('SHY', 'iShares 1-3 Year Treasury Bond ETF', 'US_BONDS', 1.0, 'LONG', 0),
('BIV', 'Vanguard Intermediate-Term Bond ETF', 'US_BONDS', 1.0, 'LONG', 0),
('VCIT', 'Vanguard Intermediate-Term Corporate Bond ETF', 'US_BONDS', 1.0, 'LONG', 0),
('VCSH', 'Vanguard Short-Term Corporate Bond ETF', 'US_BONDS', 1.0, 'LONG', 0),
('BSV', 'Vanguard Short-Term Bond ETF', 'US_BONDS', 1.0, 'LONG', 0),
('BNDX', 'Vanguard Total International Bond ETF', 'INTL_BONDS', 1.0, 'LONG', 0),
('IAGG', 'iShares Core International Aggregate Bond ETF', 'INTL_BONDS', 1.0, 'LONG', 0),
('IGOV', 'iShares International Treasury Bond ETF', 'INTL_BONDS', 1.0, 'LONG', 0),
('VTIP', 'Vanguard Short-Term Inflation-Protected Securities ETF', 'TIPS', 1.0, 'LONG', 0),
('SCHP', 'Schwab US TIPS ETF', 'TIPS', 1.0, 'LONG', 0),
('TIP', 'iShares TIPS Bond ETF', 'TIPS', 1.0, 'LONG', 0),
('VNQ', 'Vanguard Real Estate ETF', 'REAL_ESTATE', 1.0, 'LONG', 0),
('IYR', 'iShares US Real Estate ETF', 'REAL_ESTATE', 1.0, 'LONG', 0),
('SCHH', 'Schwab US REIT ETF', 'REAL_ESTATE', 1.0, 'LONG', 0),
('XLRE', 'Real Estate Select Sector SPDR Fund', 'REAL_ESTATE', 1.0, 'LONG', 0),
('RWR', 'SPDR Dow Jones REIT ETF', 'REAL_ESTATE', 1.0, 'LONG', 0),
('GLD', 'SPDR Gold Shares', 'COMMODITIES', 1.0, 'LONG', 0),
('SLV', 'iShares Silver Trust', 'COMMODITIES', 1.0, 'LONG', 0),
('IAU', 'iShares Gold Trust', 'COMMODITIES', 1.0, 'LONG', 0),
('USO', 'United States Oil Fund', 'COMMODITIES', 1.0, 'LONG', 0),
('DBC', 'Invesco DB Commodity Index Tracking Fund', 'COMMODITIES', 1.0, 'LONG', 0),
('BTC-USD', 'Bitcoin USD', 'CRYPTO', 1.0, 'LONG', 0),
('ETH-USD', 'Ethereum USD', 'CRYPTO', 1.0, 'LONG', 0),
('SOL-USD', 'Solana USD', 'CRYPTO', 1.0, 'LONG', 0),
('ADA-USD', 'Cardano USD', 'CRYPTO', 1.0, 'LONG', 0),
('XRP-USD', 'XRP USD', 'CRYPTO', 1.0, 'LONG', 0),
('DOGE-USD', 'Dogecoin USD', 'CRYPTO', 1.0, 'LONG', 0),
('AVAX-USD', 'Avalanche USD', 'CRYPTO', 1.0, 'LONG', 0),
('DOT-USD', 'Polkadot USD', 'CRYPTO', 1.0, 'LONG', 0),
('MATIC-USD', 'Polygon USD', 'CRYPTO', 1.0, 'LONG', 0),
('LINK-USD', 'Chainlink USD', 'CRYPTO', 1.0, 'LONG', 0),
('AAPL', 'Apple Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MSFT', 'Microsoft Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('GOOGL', 'Alphabet Inc Class A', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('GOOG', 'Alphabet Inc Class C', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AMZN', 'Amazon.com Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NVDA', 'NVIDIA Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('META', 'Meta Platforms Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BRK-B', 'Berkshire Hathaway Inc Class B', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TSLA', 'Tesla Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('JPM', 'JPMorgan Chase & Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('V', 'Visa Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('UNH', 'UnitedHealth Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('JNJ', 'Johnson & Johnson', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('WMT', 'Walmart Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MA', 'Mastercard Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PG', 'Procter & Gamble Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('XOM', 'Exxon Mobil Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HD', 'Home Depot Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AVGO', 'Broadcom Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MRK', 'Merck & Co Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ABBV', 'AbbVie Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CVX', 'Chevron Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('LLY', 'Eli Lilly and Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PEP', 'PepsiCo Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('KO', 'Coca-Cola Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BAC', 'Bank of America Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ADBE', 'Adobe Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('COST', 'Costco Wholesale Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MCD', 'McDonald''s Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TMO', 'Thermo Fisher Scientific Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ABT', 'Abbott Laboratories', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CSCO', 'Cisco Systems Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ACN', 'Accenture plc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CRM', 'Salesforce Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NFLX', 'Netflix Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NKE', 'Nike Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AMD', 'Advanced Micro Devices Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('INTC', 'Intel Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('INTU', 'Intuit Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ORCL', 'Oracle Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DIS', 'Walt Disney Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('WFC', 'Wells Fargo & Company', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('IBM', 'International Business Machines Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PFE', 'Pfizer Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('T', 'AT&T Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('VZ', 'Verizon Communications Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CMCSA', 'Comcast Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('QCOM', 'Qualcomm Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DHR', 'Danaher Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TXN', 'Texas Instruments Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('RTX', 'RTX Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('LIN', 'Linde plc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NEE', 'NextEra Energy Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HON', 'Honeywell International Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('UPS', 'United Parcel Service Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('GE', 'GE Aerospace', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BMY', 'Bristol-Myers Squibb Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AXP', 'American Express Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SBUX', 'Starbucks Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('GS', 'Goldman Sachs Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MS', 'Morgan Stanley', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BLK', 'BlackRock Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('LOW', 'Lowe''s Companies Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BA', 'Boeing Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AMGN', 'Amgen Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BKNG', 'Booking Holdings Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CAT', 'Caterpillar Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DE', 'Deere & Company', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('GILD', 'Gilead Sciences Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SPGI', 'S&P Global Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NOW', 'ServiceNow Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ELV', 'Elevance Health Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MDLZ', 'Mondelez International Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MMC', 'Marsh & McLennan Companies Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AMT', 'American Tower Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CB', 'Chubb Limited', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ISRG', 'Intuitive Surgical Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ADP', 'Automatic Data Processing Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ZTS', 'Zoetis Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MO', 'Altria Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TJX', 'TJX Companies Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BDX', 'Becton Dickinson and Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('REGN', 'Regeneron Pharmaceuticals Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ETN', 'Eaton Corporation plc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SO', 'Southern Company', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SLB', 'Schlumberger NV', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('EOG', 'EOG Resources Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('COP', 'ConocoPhillips', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('FCX', 'Freeport-McMoRan Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NEM', 'Newmont Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PYPL', 'PayPal Holdings Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AMAT', 'Applied Materials Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('LRCX', 'Lam Research Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('KLAC', 'KLA Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MU', 'Micron Technology Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ADI', 'Analog Devices Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MCHP', 'Microchip Technology Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PANW', 'Palo Alto Networks Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CRWD', 'CrowdStrike Holdings Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('FTNT', 'Fortinet Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ZS', 'Zscaler Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SNPS', 'Synopsys Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CDNS', 'Cadence Design Systems Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('UBER', 'Uber Technologies Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('LYFT', 'Lyft Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SQ', 'Block Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SHOP', 'Shopify Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SPOT', 'Spotify Technology SA', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('COIN', 'Coinbase Global Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HOOD', 'Robinhood Markets Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MSTR', 'MicroStrategy Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PLTR', 'Palantir Technologies Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ARM', 'Arm Holdings plc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SMCI', 'Super Micro Computer Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DELL', 'Dell Technologies Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HPQ', 'HP Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('EMR', 'Emerson Electric Co', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MMM', '3M Company', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DHI', 'D.R. Horton Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('LEN', 'Lennar Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NVR', 'NVR Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PHM', 'PulteGroup Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('WM', 'Waste Management Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('RSG', 'Republic Services Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('EW', 'Edwards Lifesciences Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SYK', 'Stryker Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MDT', 'Medtronic plc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BSX', 'Boston Scientific Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HCA', 'HCA Healthcare Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CVS', 'CVS Health Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CI', 'Cigna Group', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HUM', 'Humana Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MCO', 'Moody''s Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ICE', 'Intercontinental Exchange Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CME', 'CME Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AON', 'Aon plc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PNC', 'PNC Financial Services Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('USB', 'U.S. Bancorp', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TFC', 'Truist Financial Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('C', 'Citigroup Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SCHW', 'Charles Schwab Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TROW', 'T. Rowe Price Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('STT', 'State Street Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BK', 'Bank of New York Mellon Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('F', 'Ford Motor Company', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('GM', 'General Motors Company', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('RIVN', 'Rivian Automotive Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('LCID', 'Lucid Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TM', 'Toyota Motor Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HMC', 'Honda Motor Co Ltd', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('UNP', 'Union Pacific Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CSX', 'CSX Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NSC', 'Norfolk Southern Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('FDX', 'FedEx Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DAL', 'Delta Air Lines Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('AAL', 'American Airlines Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('UAL', 'United Airlines Holdings Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('CCL', 'Carnival Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('RCL', 'Royal Caribbean Group', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MAR', 'Marriott International Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HLT', 'Hilton Worldwide Holdings Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ABNB', 'Airbnb Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('EXPE', 'Expedia Group Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SNAP', 'Snap Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PINS', 'Pinterest Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TWTR', 'Twitter Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('RBLX', 'Roblox Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('U', 'Unity Software Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DKNG', 'DraftKings Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('APP', 'AppLovin Corporation', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TTD', 'Trade Desk Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ROKU', 'Roku Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NET', 'Cloudflare Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('MDB', 'MongoDB Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DDOG', 'Datadog Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SNOW', 'Snowflake Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('OKTA', 'Okta Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TWLO', 'Twilio Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('HUBS', 'HubSpot Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('W', 'Wayfair Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ETSY', 'Etsy Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('EBAY', 'eBay Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ZM', 'Zoom Video Communications Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('DOCU', 'DocuSign Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PTON', 'Peloton Interactive Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BYND', 'Beyond Meat Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('LI', 'Li Auto Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NIO', 'NIO Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('XPEV', 'XPeng Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('BABA', 'Alibaba Group Holding Limited', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('JD', 'JD.com Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('PDD', 'PDD Holdings Inc', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('TSM', 'Taiwan Semiconductor Manufacturing Co Ltd', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('ASML', 'ASML Holding NV', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('SAP', 'SAP SE', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NOVO-B', 'Novo Nordisk A/S', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('NVO', 'Novo Nordisk A/S ADR', 'SINGLE_STOCK', 1.0, 'LONG', 0),
('RPRX', 'Royalty Pharma plc', 'SINGLE_STOCK', 1.0, 'LONG', 0)
;
