ALTER TABLE transactions ADD COLUMN property_id INTEGER REFERENCES properties(id) ON DELETE SET NULL;
ALTER TABLE transactions ADD COLUMN vehicle_id INTEGER REFERENCES vehicles(id) ON DELETE SET NULL;
