-- 0010_seed_merchant_mappings.sql
-- Starter merchant->category seed. Patterns are matched as case-insensitive
-- substrings of the cleaned merchant name; longest match wins (see categorize.ts).
-- Extend to >=200 rows per the coverage targets in the Phase 4 plan, Task 15.
INSERT OR IGNORE INTO merchant_seed_mapping (merchant_pattern, category_id) VALUES
  ('WHOLE FOODS', 33),
  ('TRADER JOE', 33),
  ('SAFEWAY', 33),
  ('KROGER', 33),
  ('COSTCO', 33),
  ('ALDI', 33),
  ('PUBLIX', 33),
  ('SPROUTS', 33),
  ('HEB ', 33),
  ('WEGMANS', 33),
  ('FOOD LION', 33),
  ('STOP AND SHOP', 33),
  ('GIANT FOOD', 33),
  ('WINN DIXIE', 33),
  ('HARRIS TEETER', 33),
  ('STARBUCKS', 32),
  ('MCDONALD', 32),
  ('CHIPOTLE', 32),
  ('DUNKIN', 32),
  ('DOORDASH', 32),
  ('UBER EATS', 32),
  ('GRUBHUB', 32),
  ('PANERA', 32),
  ('TACO BELL', 32),
  ('SUBWAY', 32),
  ('CHICK-FIL-A', 32),
  ('CHICK FIL A', 32),
  ('BURGER KING', 32),
  ('WENDY', 32),
  ('POPEYES', 32),
  ('DOMINO', 32),
  ('PIZZA HUT', 32),
  ('FIVE GUYS', 32),
  ('PANDA EXPRESS', 32),
  ('JACK IN THE BOX', 32),
  ('SONIC DRIVE', 32),
  ('DAIRY QUEEN', 32),
  ('OLIVE GARDEN', 32),
  ('APPLEBEE', 32),
  ('IHOP', 32),
  ('DENNY', 32),
  ('SHELL', 17),
  ('CHEVRON', 17),
  ('EXXON', 17),
  ('MOBIL', 17),
  ('VALERO', 17),
  ('SUNOCO', 17),
  ('SPEEDWAY', 17),
  ('CIRCLE K', 17),
  ('BP ', 17),
  ('MARATHON PETRO', 17),
  ('CASEY GENERAL', 17),
  ('WAWA ', 17),
  ('PILOT TRAVEL', 17),
  ('LOVE TRAVEL', 17),
  ('UBER', 34),
  ('LYFT', 34),
  ('AMTRAK', 34),
  ('METRO ', 34),
  ('MTA ', 34),
  ('BART ', 34),
  ('VIA RAIL', 34),
  ('GREYHOUND', 34),
  ('UNITED AIRLINES', 22),
  ('DELTA AIR', 22),
  ('AMERICAN AIRLINES', 22),
  ('SOUTHWEST', 22),
  ('JETBLUE', 22),
  ('ALASKA AIR', 22),
  ('SPIRIT AIR', 22),
  ('FRONTIER AIR', 22),
  ('HAWAIIAN AIR', 22),
  ('AIR CANADA', 22),
  ('LUFTHANSA', 22),
  ('BRITISH AIRWAYS', 22),
  ('MARRIOTT', 23),
  ('HILTON', 23),
  ('HYATT', 23),
  ('AIRBNB', 23),
  ('IHG HOTELS', 23),
  ('WYNDHAM', 23),
  ('BEST WESTERN', 23),
  ('RADISSON', 23),
  ('HERTZ', 24),
  ('ENTERPRISE RENT', 24),
  ('AVIS', 24),
  ('BUDGET RENT', 24),
  ('NATIONAL CAR', 24),
  ('ALAMO RENT', 24),
  ('NETFLIX', 39),
  ('SPOTIFY', 39),
  ('HULU', 39),
  ('DISNEY PLUS', 39),
  ('YOUTUBE PREMIUM', 39),
  ('ADOBE', 39),
  ('AMAZON PRIME', 39),
  ('APPLE.COM/BILL', 39),
  ('MICROSOFT 365', 39),
  ('HBO MAX', 39),
  ('PEACOCK', 39),
  ('PARAMOUNT PLUS', 39),
  ('APPLE TV', 39),
  ('SLING TV', 39),
  ('DIRECTV', 39),
  ('SIRIUS XM', 39),
  ('AUDIBLE', 39),
  ('AMAZON', 37),
  ('AMZN', 37),
  ('TARGET', 37),
  ('WALMART', 37),
  ('BEST BUY', 37),
  ('EBAY', 37),
  ('ETSY', 37),
  ('NORDSTROM', 37),
  ('MACYS', 37),
  ('KOHLS', 37),
  ('TJ MAXX', 37),
  ('ROSS STORES', 37),
  ('MARSHALLS', 37),
  ('GAP ', 37),
  ('OLD NAVY', 37),
  ('H AND M', 37),
  ('ZARA', 37),
  ('LULULEMON', 37),
  ('NIKE', 37),
  ('HOME DEPOT', 11),
  ('LOWES', 11),
  ('IKEA', 13),
  ('WAYFAIR', 13),
  ('BED BATH', 13),
  ('WILLIAMS SONOMA', 13),
  ('CRATE AND BARREL', 13),
  ('COMCAST', 35),
  ('XFINITY', 35),
  ('VERIZON', 35),
  ('T-MOBILE', 35),
  ('AT AND T', 35),
  ('SPRINT', 35),
  ('DISH NETWORK', 35),
  ('COX CABLE', 35),
  ('PG AND E', 10),
  ('CON EDISON', 10),
  ('DUKE ENERGY', 10),
  ('SOUTHERN CALIFORNIA GAS', 10),
  ('PSE AND G', 10),
  ('NATIONAL GRID', 10),
  ('DOMINION ENERGY', 10),
  ('CENTERPOINT ENERGY', 10),
  ('CVS', 38),
  ('WALGREENS', 38),
  ('RITE AID', 38),
  ('KAISER', 38),
  ('UNITED HEALTH', 38),
  ('BLUE CROSS', 38),
  ('AETNA', 38),
  ('CIGNA', 38),
  ('PLANNED PARENTHOOD', 38),
  ('LABCORP', 38),
  ('GEICO', 16),
  ('PROGRESSIVE', 16),
  ('STATE FARM', 16),
  ('ALLSTATE', 16),
  ('NATIONWIDE', 16),
  ('LIBERTY MUTUAL', 16),
  ('JIFFY LUBE', 18),
  ('VALVOLINE', 18),
  ('AUTOZONE', 18),
  ('ADVANCE AUTO', 18),
  ('FIRESTONE', 18),
  ('MIDAS ', 18),
  ('AMC ', 36),
  ('REGAL', 36),
  ('TICKETMASTER', 36),
  ('STEAM GAMES', 36),
  ('PLAYSTATION', 36),
  ('XBOX ', 36),
  ('CINEMARK', 36),
  ('EVENTBRITE', 36),
  ('STUBHUB', 36),
  ('VIVID SEATS', 36),
  ('EXPEDIA', 26),
  ('BOOKING.COM', 26),
  ('HOTELS.COM', 23),
  ('PRICELINE', 26),
  ('KAYAK', 26),
  ('VRBO', 23),
  ('ORBITZ', 26),
  ('TRAVELOCITY', 26),
  ('ENTERPRISE HOLDINGS', 24),
  ('ZIPCAR', 24),
  ('PLANET FITNESS', 38),
  ('LA FITNESS', 38),
  ('ANYTIME FITNESS', 38),
  ('EQUINOX', 38),
  ('ORANGE THEORY', 38),
  ('CRUNCH FITNESS', 38),
  ('PELOTON', 38),
  ('CHEWY', 42),
  ('PETCO', 42),
  ('PETSMART', 42),
  ('USPS', 42),
  ('UPS ', 42),
  ('FEDEX', 42),
  ('DHL ', 42),
  ('INSTACART', 33),
  ('FRESH DIRECT', 33),
  ('GOOGLE PLAY', 39),
  ('APPLE SUBSCRIPTIONS', 39),
  ('DROPBOX', 39),
  ('ZOOM ', 39),
  ('SLACK ', 39),
  ('GITHUB ', 39),
  ('CANVA', 39),
  ('NORTON', 39),
  ('MCAFEE', 39),
  ('ANCESTRY', 39),
  ('MASTERCLASS', 39),
  ('DUOLINGO', 39),
  ('CHEGG', 39),
  ('COURSERA', 39),
  ('LINKEDIN PREMIUM', 39),
  ('NYTIMES', 39),
  ('WASHINGTON POST', 39),
  ('WALL STREET JOURNAL', 39),
  ('APPLE MUSIC', 39),
  ('PANDORA', 39),
  ('TIDAL ', 39),
  ('ICLOUD', 39),
  ('GOOGLE ONE', 39),
  ('LASTPASS', 39),
  ('DASHLANE', 39),
  ('NORDVPN', 39),
  ('EXPRESSVPN', 39),
  ('SQUARESPACE', 39),
  ('WIXCOM', 39),
  ('GODADDY', 39),
  ('SHOPIFY', 39),
  ('TARGET.COM', 37),
  ('COSTCO.COM', 33),
  ('SAMS CLUB', 33),
  ('BJS WHOLESALE', 33),
  ('DOLLAR GENERAL', 37),
  ('DOLLAR TREE', 37),
  ('FIVE BELOW', 37),
  ('TUESDAY MORNING', 37),
  ('BIG LOTS', 37),
  ('OVERSTOCK', 37),
  ('NEWEGG', 37),
  ('STAPLES', 37),
  ('OFFICE DEPOT', 37),
  ('WALGREENS PHOTO', 37),
  ('SHUTTERFLY', 37),
  ('APPLE STORE', 37),
  ('MICROSOFT STORE', 37),
  ('STEAM STORE', 36),
  ('NINTENDO', 36),
  ('GOOGLE STADIA', 36),
  ('TWITCH', 36),
  ('PATREON', 36),
  ('FANDANGO', 36),
  ('AMC THEATRES', 36),
  ('NATIONAL PARK', 36),
  ('ZIPLINE', 36),
  ('ESCAPE ROOM', 36),
  ('BOWLING', 36),
  ('MINI GOLF', 36),
  ('SPA ', 38),
  ('MASSAGE ENVY', 38),
  ('URGENT CARE', 38),
  ('MINUTE CLINIC', 38),
  ('QUEST DIAGNOSTIC', 38),
  ('AMERICAN FAMILY INS', 16),
  ('TRAVELERS INS', 16),
  ('USAA', 16),
  ('BRAKE CHECK', 18),
  ('OIL CHANGE', 18),
  ('PEPBOYS', 18),
  ('OCONNOR', 18),
  ('NATIONAL RENT', 24),
  ('SILVERCAR', 24),
  ('TURO ', 24);
